#!/bin/bash
sudo mkdir -p /usr/local/var/log
sudo cp locationchanger /usr/local/bin
cp LocationChanger.plist ~/Library/LaunchAgents/
launchctl unload ~/Library/LaunchAgents/LocationChanger.plist
launchctl load ~/Library/LaunchAgents/LocationChanger.plist
